import { VerticalBox, LineEdit, Button, ScrollView, CheckBox } from "std-widgets.slint";

export component WelcomeWindow inherits Window {
    width: 500px;
    height: 300px;
    title: "Todo Task Manager";

    in-out property <string> login_text;
    in-out property <string> password_text;
    in-out property <string> status_text;

    callback login_clicked;
    callback register_clicked;

    VerticalBox {
        padding: 16px;
        spacing: 12px;

        Text {
            text: "Welcome on todo task!";
            font-size: 20px;
        }

        LineEdit {
            placeholder-text: "Login";
            text <=> root.login_text;
        }

        LineEdit {
            placeholder-text: "Password";
            text <=> root.password_text;
            input-type: password;
        }

        Button {
            text: "Log in";
            clicked => {
                root.login_clicked();
            }
        }

        Button {
            text: "Register";
            clicked => {
                root.register_clicked();
            }
        }

        Text {
            text: root.status_text;
        }
    }
}


export component RegisterWindow inherits Window {
    width: 500px;
    always-on-top: true;
    background: #3e3e3e;
    height: 300px;
    title: "Registration";

    in-out property <string> login_text;
    in-out property <string> password_text;
    in-out property <string> status_text;

    callback register_clicked;

    VerticalBox {
        padding: 16px;
        spacing: 12px;

        Text {
            text: "Please write ur name and password";
            color: #ffffff;
            font-size: 20px;
        }

        LineEdit {
            placeholder-text: "Ur name";
            text <=> root.login_text;
        }

        LineEdit {
            placeholder-text: "Ur password";
            text <=> root.password_text;
            input-type: password;
        }


        Button {
            text: "Register";
            clicked => {
                root.register_clicked();
            }
        }

        Text {
            text: root.status_text;
        }
    }
}

export component UserWindow inherits Window {
    width: 700px;
    height: 800px;
    background: #3e3e3e;
    title: "Tasks";

    in-out property <string> create_task;
    in property <[string]> tasks;
    in-out property <string> status_text;

    callback create_task_clicked();

    VerticalLayout {
        padding: 20px;
        spacing: 12px;

        Text {
            text: "Tasks";
            font-size: 20px;
            horizontal-alignment: center;
            height: 40px;
            color: #ffffff;
        }

        LineEdit {
            text <=> root.create_task;
            placeholder-text: "New task";
            height: 50px;
        }

        Button {
            text: "Create task";
            height: 45px;
            clicked => {
                root.create_task_clicked();
            }
        }

        Text {
            text: root.status_text;
            color: #ffffff;
            height: 30px;
        }

        ScrollView {
            VerticalLayout {
                spacing: 10px;

                for task in tasks : Rectangle {
                    height: 40px;
                    background: #4a4a4a;
                    border-radius: 6px;

                    HorizontalLayout {
                        padding: 8px;
                        spacing: 10px;

                        CheckBox {
                            checked: false;
                            vertical-stretch: 0;
                        }

                        Text {
                            text: task;
                            color: #ffffff;
                            vertical-alignment: center;
                            horizontal-stretch: 1;
                        }
                    }
                }
            }
        }

        Rectangle {
        vertical-stretch: 1;
    }

    LineEdit {
        placeholder-text: "Task id to delete";
        height: 45px;
    }

    Button {
        text: "Delete task";
        height: 45px;
    }
    }
}